### ISSUE TITLE
href styling currently has no underline?

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#89]
In `reset.scss`, there is:

```css
a {
  text-decoration: none;
  color: inherit;
  cursor: pointer;
}
```

which stops underlining of the hyperlinks in the main page templates.

[Here](https://github.com/uzh/marugoto-frontend/pull/8) I'm adding a `underlined` class that gets `text-decoration: underline` so I don't mess with any existing styling. But can someone please let me know if there is a simple way to have underlined hrefs without the new class/css?

**Comment by interrogator** [comment]
Closing because no response and workaround fix works fine.

**Comment by christian-bernet** [comment]
In the game it was not the idea of having the link underlined.

But on the homepage it's ok in our opinion. But please define a hover state for the link.

**Comment by interrogator** [comment]
Right now hovering just gives you grab cursor. Would be cool if the text got darker or something like that, can you tell me how to add that to the css class used on main page hyperlinks, which is currently:

```css
.underlined {
  text-decoration: underline;
  color: inherit;
  cursor: pointer;
}
```
